### ISSUE TITLE
Create Handoff modal broken in Chrome, Safari

### ISSUE THREAD

**Issue by nilbus** [nilbus/handoff#13]
The modal itself is covered by the gray box that is supposed to only dim and cover everything under the modal. Nothing can be clicked. It currently only works in Firefox.

![screenshot](https://cloud.githubusercontent.com/assets/64751/6939296/358ecfb0-d839-11e4-8d24-f5c5dae19f6f.png)

**Comment by kylejmcintyre** [comment]
Apparently there is an issue in some browsers when the modal div is nested somewhere inside of a div with a fixed position. I verified that when I removed the fixed position CSS from the fixed class, the handoff modal works but of course everything is laid out all weird. The solution is to move the markup for the modals outside of that div...such as right before </body>. I'm already doing something similar to turn the datatables on dynamically so I can probably address this without too much work, but it might not be done until tonight. Is this a major blocker for you?

**Comment by kylejmcintyre** [comment]
I meant to mention in my above comment that this issue also effects other uses of modal such as the "view history" on a resource and the share handoff dialog.

**Comment by kylejmcintyre** [comment]
Actually, I was wrong about that. The problem occurs when the modal div is immediately inside of a fixed position div, so it only affects the Handoff and Share buttons. That makes it easy to fix. Stay tuned for a fix.

**Comment by nilbus** [comment]
I also removed the fixed style on the right column in my comments branch,
because fixing its position causes the comments to also be fixed on the
page, rather than scrolling with the things they're attached to.​ I don't
mind if we fix that button, but we can't fix the whole column.

**Comment by kylejmcintyre** [comment]
We could put the buttons for handoff and share in the nav section in the left margin

**Comment by nilbus** [comment]
I like that idea

**Comment by kylejmcintyre** [comment]
Do you mind if I make that change now? It may cause you some conflicts when you merge your comments branch

**Comment by nilbus** [comment]
Please go ahead.
